import { App, PluginSettingTab, Setting } from "obsidian";
import type SecondBrainTarotPlugin from "../main";
import { SpreadName } from "./spreads";
import { PROVIDER_LIST, PROVIDERS, ProviderId } from "./providers";

export interface TarotSettings {
  provider: ProviderId;
  // Per-provider, not shared — switching the provider dropdown shouldn't
  // discard a key/model you already entered for the other ones.
  apiKeys: Record<ProviderId, string>;
  models: Record<ProviderId, string>;
  defaultSpread: SpreadName;
  maxVaultChars: number;
  saveReadingsToNote: boolean;
  readingsFolder: string;
}

export const DEFAULT_SETTINGS: TarotSettings = {
  provider: "anthropic",
  apiKeys: { anthropic: "", gemini: "", grok: "" },
  models: {
    anthropic: PROVIDERS.anthropic.defaultModel,
    gemini: PROVIDERS.gemini.defaultModel,
    grok: PROVIDERS.grok.defaultModel,
  },
  defaultSpread: "three_card",
  maxVaultChars: 40_000,
  saveReadingsToNote: true,
  readingsFolder: "Readings",
};

export class TarotSettingTab extends PluginSettingTab {
  plugin: SecondBrainTarotPlugin;

  constructor(app: App, plugin: SecondBrainTarotPlugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();

    containerEl.createEl("h2", { text: "Second-Brain Tarot" });
    containerEl.createEl("p", {
      text: "Readings are generated by sending your card draw, plus relevant content from your vault, to whichever provider you pick below. Nothing leaves your machine except that request, made directly to the provider with your own key — not through any other server.",
    });

    const activeProvider = this.plugin.settings.provider;

    new Setting(containerEl)
      .setName("Provider")
      .setDesc("Which AI provider to use for interpretation. Each provider keeps its own API key and model below.")
      .addDropdown((dropdown) => {
        for (const p of PROVIDER_LIST) dropdown.addOption(p.id, p.label);
        dropdown.setValue(activeProvider).onChange(async (value) => {
          this.plugin.settings.provider = value as ProviderId;
          await this.plugin.saveSettings();
          this.display(); // re-render so the key/model fields below match the new provider
        });
      });

    new Setting(containerEl)
      .setName(`${PROVIDERS[activeProvider].label} API key`)
      .setDesc("Stored locally in this vault's plugin settings (plain text — same as most Obsidian AI plugins).")
      .addText((text) =>
        text
          .setPlaceholder("API key")
          .setValue(this.plugin.settings.apiKeys[activeProvider])
          .onChange(async (value) => {
            this.plugin.settings.apiKeys[activeProvider] = value.trim();
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Model")
      .setDesc(`Which ${PROVIDERS[activeProvider].label} model to use for interpretation.`)
      .addText((text) =>
        text
          .setPlaceholder(PROVIDERS[activeProvider].defaultModel)
          .setValue(this.plugin.settings.models[activeProvider])
          .onChange(async (value) => {
            this.plugin.settings.models[activeProvider] = value.trim() || PROVIDERS[activeProvider].defaultModel;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Default spread")
      .setDesc("Pre-selected spread when opening a new reading.")
      .addDropdown((dropdown) =>
        dropdown
          .addOptions({
            single: "Single card",
            three_card: "Three card (Past/Present/Future)",
            celtic_cross: "Celtic Cross",
            horseshoe: "Horseshoe",
            one_card_clarifier: "One card + clarifier",
            year_ahead: "Year ahead",
          })
          .setValue(this.plugin.settings.defaultSpread)
          .onChange(async (value) => {
            this.plugin.settings.defaultSpread = value as SpreadName;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Save readings as notes")
      .setDesc("When accepted, save a reading as a real note in your vault (with links back to what it drew on) instead of only showing it in the panel.")
      .addToggle((toggle) =>
        toggle.setValue(this.plugin.settings.saveReadingsToNote).onChange(async (value) => {
          this.plugin.settings.saveReadingsToNote = value;
          await this.plugin.saveSettings();
        })
      );

    new Setting(containerEl)
      .setName("Readings folder")
      .setDesc("Folder (relative to vault root) where saved readings are created.")
      .addText((text) =>
        text
          .setPlaceholder("Readings")
          .setValue(this.plugin.settings.readingsFolder)
          .onChange(async (value) => {
            this.plugin.settings.readingsFolder = value.trim() || DEFAULT_SETTINGS.readingsFolder;
            await this.plugin.saveSettings();
          })
      );
  }
}
